CREATE OR REPLACE VIEW FINANCIAL_DB.RAW_INGESTION.GOLD_STOCK_ANALYTICS AS
SELECT 
    SYMBOL,
    TRADE_DATE,
    CLOSE_PRICE,
    -- 1. 5-Day Moving Average
    AVG(CLOSE_PRICE) OVER (
        PARTITION BY SYMBOL 
        ORDER BY TRADE_DATE 
        ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_5_DAY,
    -- 2. Daily Volatility (Price Spread %)
    ((HIGH_PRICE - LOW_PRICE) / LOW_PRICE) * 100 AS DAILY_VOLATILITY_PCT,
    -- 3. Daily Return % (compared to previous day)
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE)) 
    / LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE) * 100 AS DAILY_RETURN_PCT
FROM FINANCIAL_DB.RAW_INGESTION.SILVER_STOCK_PRICES;
